# Generated by Django 4.2 on 2024-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('requestType', models.CharField(max_length=100)),
                ('companySize', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=3000)),
                ('datetime_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
